### ISSUE TITLE
Django middleware matching wrong path with path parameters

### ISSUE THREAD

**Issue by jayvdb** [zlqm/openapi-toolset#4]
Requests to `/api/oscarapi/partners/` are matching the Django path rule `/api/oscarapi/(?P<format>[^/]+)/?$` , and consequently trying to validate against `/api/oscarapi/` instead of the spec for `/api/oscarapi/partners/`.

It is *not* because of this:
```py
    def get_operation_spec(self, path, method):
        # delete ending backslash or query string
        path = re.sub(r'/?([?#].*)?$', '', path)
```

I am pretty sure it is due to `_initialize_url_rule` built regex.

This is API endpoints emitted by https://github.com/django-oscar/django-oscar-api, which uses `rest_framework.urlpatterns.format_suffix_patterns`
https://github.com/django-oscar/django-oscar-api/blob/master/oscarapi/urls.py#L310

Inside django URLConf, this path rule is defined as `/oscarapi/<drf_format_suffix:format>` , and `drf_format_suffix` is defined in DRF function `_get_format_path_converter` as r"\.[a-z0-9]+/?" .

I use https://github.com/tfranzel/drf-spectacular (master), which expresses this in the API as

```yaml
  /api/oscarapi/{format}:
    get:
      operationId: oscarapi_retrieve
      description: |-
        GET:
        Display all available urls.

        Since some urls have specific permissions, you might not be able to access
        them all.
      parameters:
      - in: path
        name: format
        schema:
          type: string
          enum:
          - .json
        required: true
```

It looks like the `enum` is being ignored when creating the path matching regex.
