### ISSUE TITLE
strict_schema, nullable and oneOf

### ISSUE THREAD

**Issue by jayvdb** [zlqm/openapi-toolset#6]
`strict_schema` does not transform the openAPI schema into a validable json schema when it contains `nullable` and `oneOf` (and probably `allOf`).

It adds `type`, and doesnt modify the `oneOf`
```yaml
oneOf:
  - type: integer
    ...
  - type: string
    ...
type: null
```

The validator ignores the `type: null` and tries to enforce the `oneOf`.  i.e. `None` is invalid, when it should be valid.

**Comment by jayvdb** [comment]
The current implementation may actually be partially correct, according to https://spec.openapis.org/oas/v3.0.3#fixed-fields-19

> (nullable) A true value adds "null" to the allowed type specified by the type keyword, only if type is explicitly defined within the same Schema Object.

The `type: null` however is being added by `strict_schema`, when according to the spec it should not be.  I am not advocating removing it yet.  That could also have bad side-effects ;-)

**Comment by zlqm** [comment]
I originally thought `nullable` means the field is not a required field, but `nullable` actually means the filed's value may be `None`. 

```yaml
oneOf:
  - type: integer
  - type: string
nullable: true
```

should be turned to 

```yaml
oneOf:
  - type: null
  - type: integer
  - type: string
```

This mistake will be fixed later. I am currently trying to add test case for this project.
